CREATE DATABASE grocery_store;

USE grocery_store;

CREATE TABLE IF NOT EXISTS supplier (
sup_id TINYINT PRIMARY KEY AUTO_INCREMENT ,
sup_name VARCHAR(255),
address TEXT
);
 
CREATE TABLE IF NOT EXISTS categories (
cat_id TINYINT PRIMARY KEY AUTO_INCREMENT,
cat_name VARCHAR(255)
);

ALTER TABLE categories
MODIFY cat_id TINYINT AUTO_INCREMENT;

DELETE

CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY AUTO_INCREMENT,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    cust_name VARCHAR(255),
    address TEXT
);

CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY AUTO_INCREMENT,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY AUTO_INCREMENT,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

DESCRIBE supplier;

# ANALYSIS QUESTIONS
# 1. CUSTOMER INSIGHTS - Gain an understanding of customer engagement and purchasing behavior.

-- How many unique customers have placed orders?
SELECT COUNT(DISTINCT(cust_id)) AS unique_cutomers FROM orders;

-- Which customers have placed the highest number of orders?
SELECT c.cust_id, c.cust_name, COUNT(o.ord_id) AS order_count
FROM customers as c LEFT JOIN orders as o 
ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name 
ORDER BY order_count DESC
LIMIT 1;

-- What is the total and average purchase value per customer?
SELECT c.cust_id, c.cust_name, SUM(od.order_total) as total_purchase_value, AVG(od.order_total) as average_purchase_value
FROM customers as c
LEFT JOIN
orders as o ON c.cust_id = o.cust_id
LEFT JOIN
(
    SELECT ord_id, SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) od ON o.ord_id=od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY c.cust_id;

-- Who are the top 5 customers by total purchase amount?
SELECT c.cust_id, c.cust_name, SUM(od.total_price) as total_purchase_value
FROM customers as c
LEFT JOIN
orders as o ON c.cust_id = o.cust_id
LEFT JOIN
order_details as od ON o.ord_id=od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase_value DESC
LIMIT 5;

# 2. Product Performance - Evaluate how well products are performing in terms of sales and revenue.
-- How many products exist in each category?
SELECT c.cat_id, c.cat_name, COUNT(p.prod_id) as count_of_products
FROM products as p
JOIN categories as c
ON p.cat_id=c.cat_id
GROUP BY c.cat_id, c.cat_name
ORDER BY c.cat_id;

-- What is the average price of products by category?
SELECT c.cat_id, c.cat_name, AVG(p.price) as avg_price
FROM products as p
LEFT JOIN categories as c
ON p.cat_id=c.cat_id
GROUP BY c.cat_id, c.cat_name
ORDER BY c.cat_id;

-- Which products have the highest total sales volume (by quantity)?
SELECT p.prod_id, p.prod_name, SUM(od.quantity) as total_quantity
FROM products as p
LEFT JOIN order_details as od
ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_quantity DESC
LIMIT 5;

-- What is the total revenue generated by each product?
SELECT p.prod_name, SUM(od.total_price) as total_revenue
FROM products as p
LEFT JOIN order_details as od
ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_revenue;

-- How do product sales vary by category and supplier?
 SELECT c.cat_id,c.cat_name, s.sup_id, s.sup_name, SUM(od.total_price) as total_revenue
 FROM products as p
 LEFT JOIN categories as c ON p.cat_id = c.cat_id
 LEFT JOIN supplier as s ON p.sup_id = s.sup_id
 LEFT JOIN order_details od ON p.prod_id = od.prod_id
 GROUP BY c.cat_id, c.cat_name, s.sup_id, s.sup_name
 ORDER BY c.cat_id, s.sup_id;
 
 # 3. Sales and Order Trends - Analyze business performance through orders and revenue over time.
 -- How many orders have been placed in total?
 SELECT COUNT(ord_id) as total_orders FROM orders;
 
 -- What is the average value per order?
 SELECT AVG(order_total) AS average_value_per_order 
 FROM(
 SELECT ord_id, SUM(total_price) as order_total
 FROM order_details
 GROUP BY ord_id
 ) as order_totals;
 
 -- On which dates were the most orders placed?
 SELECT order_date FROM orders GROUP BY order_date ORDER BY COUNT(ord_id) DESC LIMIT 1;  
 
 -- What are the monthly trends in order volume and revenue?
 SELECT 
 DATE_FORMAT(o.order_date, '%Y-%m') AS order_month,
 COUNT(DISTINCT(o.ord_id)) as total_orders,
 SUM(od.total_price) AS total_revenue
 FROM orders o
 JOIN order_details od 
 ON o.ord_id = od.ord_id
 GROUP BY order_month
 ORDER BY order_month;
 
 -- How do order patterns vary across weekdays and weekends?
 
 
 # Supplier Contribution - Identify the most active and profitable suppliers.
-- How many suppliers are there in the database?
SELECT COUNT(*) as total_suppliers FROM supplier; # sup_id is primary key, so don't need of DISTINCT

-- Which supplier provides the most products?
SELECT s.sup_id, s.sup_name, COUNT(p.prod_id) as total_products
FROM supplier s
LEFT JOIN products p
ON p.sup_id = s.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_products DESC
LIMIT 1;

-- What is the average price of products from each supplier?
SELECT s.sup_id, s.sup_name, AVG(p.price) as average_price
FROM supplier s
LEFT JOIN 
products p 
ON p.sup_id = s.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY s.sup_id;

-- Which suppliers contribute the most to total product sales (by revenue)?
SELECT s.sup_id, s.sup_name, SUM(od.total_price) as total_product_sales
FROM supplier s
LEFT JOIN
products p 
ON p.sup_id = s.sup_id
LEFT JOIN order_details od
ON od.prod_id = p.prod_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_product_sales DESC;

# 5️. Employee Performance - Assess how employees are handling and influencing sales.
-- How many employees have processed orders?
SELECT COUNT(DISTINCT(emp_id)) FROM orders;

-- Which employees have handled the most orders?
SELECT emp_id, COUNT(ord_id) as total_orders FROM orders GROUP BY emp_id ORDER BY total_orders DESC LIMIT 1;

-- What is the total sales value processed by each employee?
SELECT 
    e.emp_id,
    e.emp_name,
    SUM(od.total_price) AS total_sales_value
FROM employees e
JOIN orders o 
    ON e.emp_id = o.emp_id
JOIN order_details od 
    ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_sales_value DESC;

-- What is the average order value handled per employee?
SELECT AVG(
SELECT AVG(